apiVersion: v1
kind: Service
metadata:
  name: {{ include "osspilot.fullname" . }}
  labels:
    {{- include "osspilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: tenant-worker
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "osspilot.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
