{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osspilot.secretName" . }}
  labels:
    {{- include "osspilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  projection-secret: {{ .Values.projection.secret | quote }}
  database-url: {{ .Values.database.url | quote }}
{{- end }}
